feat: 오디오 프록시 서버 구현
Team-Orm/the-beat-server pull request #15
Opened 2023-03-20 14:38 UTC by shuh319

## 📝 Description
클라이언트에서 Amazon s3 링크 `audioURL`을 받아서 Web audio api로 `audioURL`을 로딩하는 과정에 CORS 문제가 있었습니다. 
해결을 위해 오디오 프록시 서버를 구현하였습니다. 

## ❗ Related Issues
N/A

## 🛠️ Changes
- `controllers` 폴더에 `proxy.Controller.js` 추가하여 오디오 버퍼 가져오는 함수인 `getBuffer`를 추가하였습니다. 유효하지 않은 `audioURL`의 경우에 status 400을 보내고 유효할 경우 응답으로 오디오버퍼배열을 줍니다. 
- 프록시 서버를 위한 새로운 라우터 `proxyRouter`를 추가하였습니다. 

## 📸 Screenshot

2023-03-20 19:37 UTC, HyukE reviewed
PR에 왜 이번 프로젝트에서 프록시 서버를 구현 해야했는지 이유를 추가해주시면 좋은거 같아요!
또한 `package-lock.json`확인이 필요해 보입니다🤔

2023-03-20 19:37 UTC, HyukE commented on package-lock.json
> +=======
```
<<<<<<< HEAD
    "node_modules/delayed-stream": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz",
      "integrity": "sha512-ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ==",
      "engines": {
        "node": ">=0.4.0"
=======
```
```
<<<<<<< HEAD
=======
``` 
이부부은  무엇이죠?????????

2023-03-20 19:37 UTC, HyukE commented on package-lock.json
> +>>>>>>> origin/dev
`>>>>>>> origin/dev` 이 왜 생겼나요? 제생각에는 CONFLICT 가 생긴거 같습니다.

2023-03-20 19:37 UTC, HyukE commented on package-lock.json
> +=======
이부분 도 확인이 필요해 보입니다.

2023-03-20 19:37 UTC, HyukE commented on package-lock.json
> +>>>>>>> origin/dev
확인 필요!

2023-03-20 19:37 UTC, HyukE commented on src/routes/controllers/proxy.Controller.js
> +      console.log(response.data);
```suggestion
```
불필요한 코드는 지워주세요!

2023-03-21 05:23 UTC, oyobbeb requested changes
`package-lock.json`에 수정이 필요해 보입니다!

2023-03-21 05:23 UTC, oyobbeb commented on package-lock.json
> +=======
🧐

2023-03-21 05:23 UTC, oyobbeb commented on package-lock.json
> +    },
어떤 `library` 때문에 설치된 것인지 알  수 있을까요?

2023-03-21 05:23 UTC, oyobbeb commented on package-lock.json
> +    },
`axios`의 버전이 client와 맞는 지에 대해서도 확인할 필요가 있어 보여요!

2023-03-21 05:23 UTC, oyobbeb commented on package-lock.json
> +>>>>>>> origin/dev
🧐

2023-03-21 05:23 UTC, oyobbeb commented on src/routes/controllers/proxy.Controller.js
> +  const audioURL = req.query.url;
`query`로 주는 것과 `POST`로 직접 주소값을 보내는 것의 차이가 무엇이 있을까요?

2023-03-21 09:11 UTC, oyobbeb approved these changes
변경사항 확인하였습니다!

2023-03-21 09:13 UTC, HyukE approved these changes
변경사항 확인 완료 했습니다!

2023-03-21 09:20 UTC, merged